### ISSUE TITLE
loqed opnieuw instaleren  in HA 

### ISSUE THREAD

**Issue by tremelohome** [mikewoudenberg/homeassistant-loqed#15]
Ik probeer om loqed opnieuw te instaleren in HA maar geraak niet verder.  Kan de Uitgaande webhooks via LOQED Bridge  niet verwijderen.  Dus vind HA het slot wel maar wil dan niet verbinden?  Dit voer ik ook uit chrome://flags/#block-insecure-private-network-requests  maar kom dus niet verder de webhooks blijven staan.

Dit doe ik Login at LOQED's [personal access tokens portal](https://integrations.loqed.com/personal-access-tokens) and:

Create an API-key by clicking 'Create'
Copy the created access token.

Dan creeer ik de token maar deze wordt niet gevonden.   zou volgens mik (loqed) een timestamp probleem kunnen zijn.  10 sec verschil tussen HA en  ???

Kan je me helpen???  HA is up to date en loqed sloten 2 twee werken via de app.  Maar worden niet gevonden in HA

**Comment by tremelohome** [comment]
Logger: homeassistant.components.websocket_api.http.connection
Bron: components/websocket_api/connection.py:301
integratie: Home Assistant WebSocket API ([documentatie](https://www.home-assistant.io/integrations/websocket_api), [problemen](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
Eerst voorgekomen: 20:55:12 (3 gebeurtenissen)
Laatst gelogd: 20:57:01

[140147406973888] Error handling message: Unknown device '75d2d86013fc0599e67ff284b69ecfc5' (home_assistant_error) mijn naam from 127.0.0.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Agency/98.8.7987.78)


Heb nu wel een slot dat zichtbaar is maar kan niets aansturen.  Heb blijkbaar nog steeds de oude key die ik niet kan verwijderen..  Niet toegewezen sleutel "delete me" access old client (old api key heeft deur geopend

**Comment by mikewoudenberg** [comment]
Hey tremelohome,

Thanks for reaching out. First things first: this is the repository for the custom component version of the Loqed integration. It currently is at feature parity with the official integration, so no need to have it installed, I use it for testing new features. 

I'd recommend starting off clean, removing the instance from home assistant and the hooks from the bridge. Then restart home assistant and it should automatically discover your lock(s). 

The timing issue is interesting. The integration checks incoming messages for their timestamp and rejects everything outside +-10 sec from the current server time. The bridge/lock does the same for incoming messages from the server. 

Please enable debug logging in home assistant by performing the service call shown in https://support.loqed.com/en/articles/6144029-home-assistant-loqed-integration and verify whether you see any messages from the integration mentioning issues with processing messages because of timestamp

**Comment by tremelohome** [comment]
opnieuw alles verwijderd overal dus app sleutels api key enz en ook de vertaling van google translate uitgezet en dit werkt terug thankx

**Comment by mikewoudenberg** [comment]
So this means the issue can remain closed now? In that case, glad it worked out for you!
