### ISSUE TITLE
Can't find Loqed in HACS

### ISSUE THREAD

**Issue by Kopernikus1979** [mikewoudenberg/homeassistant-loqed#4]
Hi,

I can't seem to find Loqed in the HACS repository.

Any idea?

**Comment by mikewoudenberg** [comment]
Hi that's correct. I haven't added it to that quite yet. You can add it as custom repository via HACS if you're really adventurous. I can't find a guide on HACS documentation site (https://hacs.xyz/) to point you to, but you can do it via the hamburger menu in the HACS pane in Home Assistant.

**Comment by robertwebbe** [comment]
@mikewoudenberg 

I've read your message above but since the README.md contains the text

Installation with HACS (Home Assistant Community Store)
1) Ensure that HACS is installed.
**2) Search for and install the Loqed integration through HACS**.

I guess you've added it. But when I search, another custom component (https://github.com/cpolhout/loqed_custom_component) is found. So, is the README text not correct than?

**Comment by mikewoudenberg** [comment]
I'll ask cpolhout to remove his version so this one pops up. At this moment the README is indeed incorretc and you need to add it manually via custom repository.

**Comment by mikewoudenberg** [comment]
Hmm if I search in HACS I don't get any results. So maybe you just found the custom repository you added earlier. I'm working on getting this into HACS atm.

**Comment by mikewoudenberg** [comment]
Just found out that custom_components are not meant to be used as beta test functionalities via the HACS system. updated the README to reflect this, ie. that you can only use this by adding it as a custom repo to HACS
